apiVersion: v1
kind: Pod
metadata:
  name: pvc-reader
spec:
  restartPolicy: Never
  containers:
    - name: reader
      image: busybox:latest
      command:
        - /bin/sh
        - -c
        - |
          echo "Listando arquivos em /data:"
          ls -la /data
          echo "Conteudo do arquivo registro.txt:"
          cat /data/registro.txt
          sleep 3600
      volumeMounts:
        - name: todo-volume
          mountPath: /data
  volumes:
    - name: todo-volume
      persistentVolumeClaim:
        claimName: todo-pvc
